services:
  db:
    image: docker.1ms.run/library/postgres:15
    container_name: gdelt_db
    restart: always
    environment:
      - "POSTGRES_USER=zhenxian"
      - "POSTGRES_PASSWORD=15821828225Lzx!"
      - "POSTGRES_DB=dgelt"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zhenxian -d dgelt"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: gdelt_backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - "DB_URL=postgresql+psycopg2://zhenxian:15821828225Lzx!@db/dgelt"
    command: python3 main_service.py
    volumes:
      - .:/app
      - ./logs:/app/logs

  frontend:
    build: .
    container_name: gdelt_frontend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - "DB_URL=postgresql+psycopg2://zhenxian:15821828225Lzx!@db/dgelt"
    ports:
      - "8095:8090"
    command: python3 web/app.py
    volumes:
      - .:/app
