services:
  db:
    image: 1ms.docker.run/library/postgres:15
    container_name: gdelt_db
    restart: always
    environment:
      POSTGRES_USER: zhenxian
      POSTGRES_PASSWORD:   vbn
      POSTGRES_DB: dgelt
    ports:
      - "5432:5432"
    volumes:
      # 使用宿主机目录挂载，方便您在服务器上看到物理文件
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zhenxian -d dgelt"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: gdelt_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://zhenxian:  vbn@db/dgelt
    command: python3 main_service.py
    volumes:
      - ./logs:/app/logs

  frontend:
    build: .
    container_name: gdelt_frontend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://zhenxian:  vbn@db/dgelt
    ports:
      - "8090:8090"
    command: python3 web/app.py
